name: SAM3/ufmt
on:
  pull_request:
    branches:
    - main
jobs:
  ufmt_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check formatting
        uses: omnilib/ufmt@action-v1
        with:
          path: sam3 scripts
          python-version: "3.12"
          black-version: "24.2.0"
          usort-version: "1.0.2"
